#include: package:lint/analysis_options.yaml

#analyzer:
#  errors:
#    missing_required_param: error
#    # treat missing returns as a warning (not a hint)
#    missing_return: error
#    must_be_immutable: error
